export const STATE_LOADING = 'LOADING'
export const STATE_POST_ORDER = 'STATE_POST_ORDER'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_BY_CATEGORY_ID = 'FETCH_POSTS_BY_CATEGORY_ID'
export const FETCH_POST_DETAIL = 'GET_POST_DETAIL'
export const FETCH_COMMENTS_BY_POST_ID = 'FETCH_COMMENTS_BY_POST_ID'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'