export const STATE_LOADING = 'LOADING'
export const STATE_POST_ORDER = 'STATE_POST_ORDER'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_BY_CATEGORY_ID = 'FETCH_POSTS_BY_CATEGORY_ID'
export const FETCH_POST_DETAIL = 'GET_POST_DETAIL'
export const VOTE_POST = 'VOTE_POST'
export const DELETE_POST = 'DELETE_POST'

export const FETCH_COMMENTS_BY_POST_ID = 'FETCH_COMMENTS_BY_POST_ID'
export const VOTE_COMMENT = 'VOTE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'